# This is a basic workflow to help you get started with Actions

name: Moizshah_react_project-01

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branchon 
on:

  push:
    branches: [ main ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Install Node
      uses: action/setup-node@v2-beta
      with:
        node-version: 12
    
    - name: Install Surge
      run: npm install --global surge

    - name: Deploy using Surge
     # run: surge ./moizshah-react-project-01.surge.sh --token ${{ secrets.PROJECTS}}
      run: surge./moizshah-react-project-01.surge.sh --token "411e7a129efe4681fa011e30e7d9a0b2"
